config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resource :users do
    resource :sessions, only: [:new, :create, :destroy]
    resources :posts do
      resources :comments
    end
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'

  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    belongs_to :user
    has_and_belongs_to_many :tags

    validates :title, presence: true
    validates :article, presence: true

end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true

    has_many :comments, dependent: :destroy
    has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :authorized
    helper_method :current_user
    helper_method :logged_in?

    def current_user
        User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def authorized
        redirect_to welcome_path unless logged_in?
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def index
        @comments = Comment.all
        
    end

    def new
        @comment = Comment.new(post_id: params[:post_id])
    end

    def create
        @comment = Comment.new(comments_params)
        @comment.name = current_user.name
        @comment.user_id = current_user.id
        @comment.post_id = params[:post_id]
        p "....DONE!!!!!!!!! #{@comment.inspect}"

        if @comment.save
            redirect_to users_post_path(params[:post_id])
        else
            render :new
        end
    end

    def destroy
        @comment = Comment.find(params[:post_id])
        @comment.destroy

        redirect_to users_post_path
    end

end

private
    def comments_params
        params.require(:comment).permit(:name, :message)
    end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
        @tags = Tag.all

        
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(posts_params)
        @post.user_id = current_user.id

        p "....DONE!!!!!!!!! #{@post.inspect}"

        if @post.save
            redirect_to root_url
        else
            render :new
        end

        
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy

        redirect_to root_url
    end

    def show
        @post = Post.find(params[:id])
        @user = @post.user
        @comments = @post.comments.all
        
        
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        @post.update(posts_params)
        redirect_to users_post_path
    end
end


private
    def posts_params
        params.require(:post).permit(:title, :article, :img_url)
    end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])

    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id

      redirect_to welcome_path
    else
      redirect_to login_path
    end

    def destroy
      session[:user_id] = nil

      redirect_to welcome_path
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
        @tags = Tag.all
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    skip_before_action :authorized, only: [:new, :create]
    
    def new
        @user = User.new
    end

    def create
        @user = User.new
        @user.name = params[:user][:name]
        @user.email = params[:user][:email]
        @user.password = params[:user][:password]
        @user.password_confirmation = params[:user][:password_confirmation]

        if @user.save
            flash[:success] = "Welcome #{@user.name} to BlogOn!"

            redirect_to users_posts_path
        else
            render :new
        end
    end

    def destroy
        @user = User.find_by(params[:id])
      if @user && @user == current_user
        session[:user_id] = nil
      end
      @user.destroy
  
      redirect_to welcome_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1>What would you like to comment?</h1>

<%= form_for [@post, @comment], url: users_post_comments_path, method: :post do |p| %>
    <p>
<%= p.label "Message:" %><br>
<%= p.text_field :message %>
    </p>
    <p>
<%= p.submit "Post your Comment!", :class => "button" %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<%= stylesheet_link_tag "global" %>
<%= stylesheet_link_tag "nav" %>


<!DOCTYPE html>
<html>
  <head>
    <title>Blogon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag :application %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <div class="navbar">
        <p class="leftside"><a href="/users/posts"><%= image_pack_tag 'media/packs/images/blogon.png' %></a></p>
        <p><%= link_to "Home", users_posts_path %></p>
        <p><%= link_to "Create Post", new_users_post_path %></p>
        <div class="rightside">
        <% if logged_in? %>
          <p><%= link_to "Log Out", users_sessions_path, method: :delete %></p>
          <p><%= link_to "Delete Account", users_path, method: :delete, data: { confirm: "Are you sure? \nYou will lose all your posts, and won't be able to recover them!" }%></p>
          <p class="own">You are logged in, <%= current_user.name %></p>
        <% else %>
          <p><%= link_to "Sign Up", new_users_path %></p>
          <p><%= link_to "Login", login_path %></p>
        <%end%>
      </div>
    </div>
  </header>

  <div class="main">
    <body>
      <%= yield %>
    </body>
  </div>
</html>

app/views/posts/edit.html.erb
<h1>Edit your thoughts on BlogOn</h1>

    <%= form_for @post, url: users_post_path do |p| %>
        <p>
    <%= p.label "Title:" %><br>
    <%= p.text_field :title %>
        </p>
        <p>
    <%= p.label "Article:" %><br>
    <%= p.text_field :article %>
        </p>
        <p>
    <%= p.label "Picture link for the Article (optional):" %><br>
    <%= p.text_field :img_url %>
        </p>
        <p>
    <%= p.submit "Update your Thought!", :class => "button" %>
        </p>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |p| %>
    <div class="container">

    <div class="title">
    <h2><%= p.title %></h2>
    </div>
    <div>
    <img src="<%= p.img_url %>">
    </div>
    <div class="article">
    <p><%= p.article %></p>
    </div>
    <div class="buttonlocat">
    <div>
    <h5><%= p.comments.count %> Comments</h5>
    </div>
    <button class="button"><%= link_to "Show More", users_post_path(p) %></button>
    <button class="button"><%= link_to "Edit Post", edit_users_post_path(p) %></button>
    <button class="delete"><%= link_to "Delete Post", users_post_path(p), method: :delete, data: { confirm: 'Are you sure?' } %></button>
    </div>
    </div>
<%end%>

app/views/posts/new.html.erb
<h1>Compose your thoughts on BlogOn</h1>

    <%= form_for @post, url: users_posts_path do |p| %>
        <p>
    <%= p.label "Title:" %><br>
    <%= p.text_field :title %>
        </p>
        <p>
    <%= p.label "Article:" %><br>
    <%= p.text_field :article %>
        </p>
        <p>
    <%= p.label "Picture link for the Article (optional):" %><br>
    <%= p.text_field :img_url %>
        </p>
        <p>
    <%= p.submit "Post your Thought!" %>
        </p>
<% end %>

app/views/posts/show.html.erb
<div class="container">
<h1 class="title"><%= @post.title %></h1>
<h3 class="writer">Written by <%= @user.name %></h3>
<div class="buttonlocat">
<button class="button"><%= link_to "Add Comment", new_users_post_comment_path(@post) %></button>
<button class="button"><%= link_to "Edit Post", edit_users_post_path(@post) %></button>
<button class="delete"><%= link_to "Delete Post", users_post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %></button>
</div>
    <img src="<%= @post.img_url %>">
    <p class="article"><%= @post.article %></p>
    <hr>
<div class="comments">
    <h2 class="c_title">Comments:</h2>
    <% @post.comments.each do |c| %>
        <div class="comment_contain">
        <h4><%= c.name %> said:</h4>
        <p><%= c.message %></p>
        <button class="delete"><%= link_to "Delete Comment", users_post_comment_path(c), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' } %></button>
    <% end %>
    </div>
    </div>
    </div>

app/views/tags/index.html.erb
<% @tags.each do |t| %>
    <p><%= t.name %></p>
<% end %>

app/views/users/new.html.erb
<h1> Create Account </h1>

<% if @user.errors.any? %>
    <ul>
        <% @user.errors.full_messages.each do |m| %>
            <li>
                <%= m %>
            </li>
        <% end %>
    </ul>
<% end %>
<div class="new_account">
<%= form_for @user, url: users_path do |u| %>
    <p>
<%= u.label "Name:" %><br>
<%= u.text_field :name %>
    </p>
    <p>
<%= u.label "Email:" %><br>
<%= u.text_field :email %>
    </p>
    <p>
<%= u.label "Password:" %><br>
<%= u.password_field :password %>
    </p>
    <p>
<%= u.label "Password Confirmation:" %><br>
<%= u.password_field :password_confirmation %>
    </p>
    <p>
<%= u.submit "Sign Up!", :class => "button" %>
    </p>
<% end %>
</div>